site_name: bz-cli
site_url: https://dbuzinski.github.io/bz-cli
site_description: A tool for reproducible and efficient training of AI models.
site_author: David Buzinski

theme:
  name: darkly

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide: user-guide.md
  - Developer Guide: developer-guide.md
  - About: about.md

plugins:
  - search
  - mkdocstrings:

markdown_extensions:
  - codehilite
  - toc:
      permalink: '#'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dbuzinski/bz-cli

extra_javascript:
  - js/copy-codeblock.js

extra_css:
  - css/custom.css
