[project]
name = "bz-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.5",
    "standard-imghdr>=3.13.0",
    "tensorboard>=2.19.0",
    "torch>=2.7.0",
    "tqdm>=4.67.1",
]

[tool.setuptools.packages.find]
where = ["./"]
include = ["bz", "bz.plugins", "bz.metrics"]

[project.scripts]
bz = "bz.cli:main"
