name: Publish Docs
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs mkdocs-bootswatch mkdocstrings[python] pymdown-extensions
      - run: mkdocs gh-deploy --force --clean --verbose
