name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          prune-cache: false
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install build tools
        run: uv add --dev hatch
      - name: Build package
        run: uv build
      - name: Publish to PyPI
        run: uv publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
